name: TestRun-1-Mystic-ov-26-with-Python

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      n:
        description: '실행 횟수'
        required: false
        default: '10'
        type: string

run-name: TestRun-1-Mystic-ov-26-with-Python [${{ github.event.inputs.n || '10' }}]

concurrency:
  group: my-workflow-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Run Python script
      run: python script.py ${{ github.event.inputs.n || '10' }}
